# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- template: azure-pipelines-steps.yml
  parameters:
    name: test1
    displayName: 'Test econml'
    package: '"econml==0.9.0b1" dowhy IPython'
    body:
      - script: 'pip install pytest pytest-cov pytest-xdist && python -m pytest'
        displayName: 'Unit tests'
        env:
          PYTEST_ADDOPTS: '-m "not (notebook or automl)"'
          COVERAGE_PROCESS_START: 'setup.cfg'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results **/test-results.xml'
        inputs:
          testResultsFiles: '**/test-results.xml'
          testRunTitle: 'Python $(python.version), image $(imageName)'
        condition: succeededOrFailed()
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage Results'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

- template: azure-pipelines-steps.yml
  parameters:
    name: test2
    displayName: 'Test shap'
    package: '"numpy==1.19.3" shap'
    body:
      - script: 'pip install pytest pytest-cov pytest-xdist && python -m pytest'
        displayName: 'Unit tests'
        env:
          PYTEST_ADDOPTS: '-m "shap"'
          COVERAGE_PROCESS_START: 'setup.cfg'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results **/test-results.xml'
        inputs:
          testResultsFiles: '**/test-results.xml'
          testRunTitle: 'Python $(python.version), image $(imageName)'
        condition: succeededOrFailed()
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage Results'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

